### ISSUE TITLE
[agu2019] Update AGU template to include Open Research/Availability Statement recent changes

### ISSUE THREAD

**Issue by libcce** [curvenote/templates#44]
AGU recently updated our template to include the Open Research section which includes the Data/Software Availability Statements https://www.agu.org/Publish-with-AGU/Publish per our data/software guidance for authors https://www.agu.org/Publish-with-AGU/Publish/Author-Resources/Data-and-Software-for-Authors

**Comment by stevejpurves** [comment]
@libcce thanks for opening this issue 👏.
We'll make those changes for sure.
