### ISSUE TITLE
required boolean options don't make sense e.g. [SPIE]

### ISSUE THREAD

**Issue by stevejpurves** [curvenote/templates#45]
Currently, the SPIE template has the option `type: boolean` and `required: true` which is permitted by our schema but doesn't make sense. As it would require the setting to be `true` always 🤔

 1. fix the template
 2. is here something that we can do to prevent this - at least documentation if not a schema change

**Comment by rowanc1** [comment]
My take on required is that it is provided, not necessarily true? If the option is always true, not much of an option. :)

For booleans I can see that this doesn't make much sense. There could be three states in the UI I suppose, undefined, false, true. Similar to JavaScript.

**Comment by stevejpurves** [comment]
yeah, it's how the UI interprets the required flag - at the moment that is interpreted as the user must supply an answer, rather than the field must be set on the response but boolean it the case that is strange. Just going to remove required from the template for now.
