### ISSUE TITLE
Should our default template abstract be plain text?

### ISSUE THREAD

**Issue by rowanc1** [curvenote/templates#55]
I think that maybe not?

This is what I got, which isn't great.

![image](https://user-images.githubusercontent.com/913249/144518145-b2c8e241-435c-457e-afac-81c04772f1e7.png)

**Comment by stevejpurves** [comment]
fixed in #59 

![image](https://user-images.githubusercontent.com/1473646/144592135-a6ec729f-89c4-4ed6-bfad-8eb27001fe93.png)
