### ISSUE TITLE
SPIE template authors are repeated.

### ISSUE THREAD

**Issue by rowanc1** [curvenote/templates#7]
![image](https://user-images.githubusercontent.com/913249/126703500-a5c9e1d2-c2a1-47ef-8207-5c2ad98ba0a1.png)

**Comment by stevejpurves** [comment]
ok, reproduced this. It happens for any template where there are multiple Curvenote users and is a problem with our templatings code rather than the template.

**Comment by stevejpurves** [comment]
fixed
