### ISSUE TITLE
Hanging affiliations breaks latex

### ISSUE THREAD

**Issue by rowanc1** [curvenote/templates#75]
If one of the authors does not have an affiliation, then the make title will fail, and then bibtex won't parse.

https://github.com/curvenote/templates/blob/main/latex/default/template.tex#L27

![image](https://user-images.githubusercontent.com/913249/152870542-2fae8d97-8821-47c3-86b2-3ec393de109f.png)

**Comment by stevejpurves** [comment]
@rowanc1 should be fixed!
