### ISSUE TITLE
Multiline equations do not render in Curvenote Default PDF/Latex exports

### ISSUE THREAD

**Issue by mrava87** [curvenote/templates#89]
Hello,
I am writing a paper with Curvenote and I noticed that when I try to export latex/pdf with `Curvenote Default`, multiline equations* do not render.

*A multiline equation is an equation written within `$$..$$` and using
```
\begin{split}
...
\end{split}
```

**Comment by mrava87** [comment]
Oh I see, let me try :)

**Comment by stevejpurves** [comment]
@mrava87 did this work out for you?

**Comment by mrava87** [comment]
Yes :D

In curvenote, it seems like this trick created double numbering but when I export it I only get the relevant one.

<img width="683" alt="Screen Shot 2022-08-12 at 5 39 21 PM" src="https://user-images.githubusercontent.com/22675848/184378748-b5608154-e444-4430-91ff-d656b2c07a5a.png">

**Comment by stevejpurves** [comment]
@mrava87 I take it you saw that double numbering when looking at a curvenote website with `curvneote start`?

**Comment by mrava87** [comment]
I am using the curvenote web-editor

**Comment by stevejpurves** [comment]
closing this issue, the duplicated numbering we will pick up in https://github.com/curvenote/curvenote/issues/136
